import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const date = '2026-07-15';
const category = 'Real-time Computer Vision';
const categoryKey = 'rt';

const papers = [
  ['attention-is-all-you-need', 'Attention Is All You Need', 'Attention만 있으면 된다', '2017', 'NeurIPS', 'https://arxiv.org/abs/1706.03762', 'https://github.com/tensorflow/tensor2tensor', 'Transformer', 'self-attention으로 입력 토큰 사이의 관계를 병렬로 계산해, 순차 모델 없이도 긴 시퀀스를 처리하는 구조를 제시했다.', '시각·언어·로봇 상태·행동을 하나의 token 시퀀스로 다루는 VLA의 공통 언어다.', 'attention map, positional encoding, encoder-decoder, autoregressive decoding', 'attention score, positional encoding'],
  ['vision-transformer', 'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale', '이미지를 패치 토큰으로 읽는 Vision Transformer', '2020', 'ICLR 2021', 'https://arxiv.org/abs/2010.11929', 'https://github.com/google-research/vision_transformer', 'Vision Transformer', '이미지를 고정 크기 patch들의 시퀀스로 바꾸고 Transformer로 분류하는 ViT를 제안해 VLM의 시각 encoder 계보를 열었다.', 'VLA에서 카메라 영상이 언어·행동과 결합되기 전 어떤 시각 token이 만들어지는지 이해하게 한다.', 'patch embedding, class token, large-scale pretraining, transfer learning', 'patch embedding, class token'],
  ['clip', 'Learning Transferable Visual Models From Natural Language Supervision', '자연어로 시각 개념을 정렬하는 CLIP', '2021', 'ICML', 'https://arxiv.org/abs/2103.00020', 'https://github.com/openai/CLIP', 'CLIP', '이미지와 텍스트를 같은 표현 공간에 정렬해, 학습하지 않은 범주도 자연어 class prompt로 구분할 수 있게 했다.', '언어 지시가 영상의 물체·속성을 가리키는 VLA grounding의 출발점이다.', 'contrastive learning, image-text embedding, zero-shot classification, prompt', 'contrastive learning, zero-shot'],
  ['decision-transformer', 'Decision Transformer: Reinforcement Learning via Sequence Modeling', '보상 조건을 포함한 행동 시퀀스 모델링', '2021', 'NeurIPS', 'https://arxiv.org/abs/2106.01345', 'https://github.com/kzl/decision-transformer', 'Decision Transformer', '강화학습을 상태·행동·목표 보상의 조건부 다음 token 예측으로 다시 쓴 모델이다.', 'VLA가 장기 목표와 과거 행동을 한 문맥에서 다루는 방법을 이해하는 데 유용하다.', 'return-to-go, trajectory tokenization, offline RL, conditional generation', 'return-to-go, offline RL'],
  ['saycan', 'Do As I Can, Not As I Say: Grounding Language in Robotic Affordances', '언어 계획을 로봇의 실제 가능성에 접지하는 SayCan', '2022', 'CoRL', 'https://arxiv.org/abs/2204.01691', 'https://say-can.github.io/', 'SayCan', '언어 모델이 제안한 skill을 가치 함수의 실행 가능성으로 재순위화해, 긴 자연어 지시를 실제 로봇 행동으로 연결한다.', 'end-to-end VLA 이전의 안전한 모듈형 기준선이며 PTZ 운영 규칙과도 잘 맞는다.', 'LLM planning, affordance score, value function, skill library', 'affordance, value function'],
  ['vima', 'VIMA: General Robot Manipulation with Multimodal Prompts', '텍스트·이미지·예시를 하나의 prompt로 다루는 VIMA', '2022', 'ICML', 'https://arxiv.org/abs/2210.03094', 'https://github.com/vimalabs/VIMA', 'VIMA', '텍스트, goal image, one-shot demonstration을 interleaved prompt로 만들고 조작 행동을 autoregressive하게 생성한다.', '목표를 말·사진·시연으로 주는 방식의 일반화 차이를 체계적으로 비교할 수 있다.', 'multimodal prompt, object tokens, simulation benchmark, generalization', 'multimodal prompt, goal image'],
  ['rt-1', 'RT-1: Robotics Transformer for Real-World Control at Scale', '실제 로봇 데이터로 확장한 Robotics Transformer', '2022', 'Robotics: Science and Systems', 'https://arxiv.org/abs/2212.06817', 'https://robotics-transformer1.github.io/', 'RT-1', '다양한 실제 로봇 데모와 Transformer policy를 함께 키우면 새로운 물체·지시·장면에서 전이가 좋아진다는 것을 보였다.', 'VLA가 왜 단일 과제 모델이 아니라 데이터 다양성을 가진 foundation policy로 향했는지 설명한다.', 'TokenLearner, action tokenization, data diversity, real-world scaling', 'action tokenization, data diversity'],
  ['palm-e', 'PaLM-E: An Embodied Multimodal Language Model', '연속 센서를 언어 모델에 접지한 PaLM-E', '2023', 'ICML', 'https://arxiv.org/abs/2303.03378', 'https://palm-e.github.io/', 'PaLM-E', '시각·로봇 상태 같은 연속 입력을 언어 token과 섞어 대형 언어 모델이 여러 embodiment의 계획·질문·조작을 함께 다루게 한다.', '웹 지식과 현장 센서가 한 모델에서 만나지만, 실제 상태 검증이 여전히 필요함을 보여 준다.', 'embodied token, multimodal sentence, positive transfer, robot state', 'embodied language model, grounding'],
  ['rt-2', 'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control', '웹 지식을 행동 token으로 옮긴 RT-2', '2023', 'CoRL', 'https://arxiv.org/abs/2307.15818', 'https://robotics-transformer2.github.io/', 'RT-2', 'vision-language pretraining의 의미 지식을 로봇 행동 token 예측에 전이해, 보지 못한 물체와 표현에 대한 일반화를 보였다.', 'VLA라는 이름을 대표적으로 굳힌 연구이며 semantic generalization과 제어 정확도의 간극을 읽어야 한다.', 'VLM co-fine-tuning, action as tokens, web knowledge, semantic generalization', 'VLA, semantic generalization'],
  ['robocat', 'RoboCat: A Self-Improving Generalist Agent for Robotic Manipulation', '자기 생성 데이터로 확장하는 RoboCat', '2023', 'arXiv preprint', 'https://arxiv.org/abs/2306.11706', 'https://www.deepmind.com/blog/robocat-a-self-improving-robotic-agent', 'RoboCat', '다른 로봇과 task의 시각 목표 데모를 학습하고, 새 task에서 적응한 뒤 자신의 성공 rollout을 다음 학습 데이터로 쓰는 순환을 제시한다.', '현장 실패/성공 로그를 다시 데이터 자산으로 만드는 운영 관점과 연결된다.', 'multi-embodiment, goal-conditioned policy, self-improvement, adaptation', 'goal-conditioned policy, self-improvement'],
  ['act-aloha', 'Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware', 'Action Chunking Transformer와 ALOHA', '2023', 'RSS', 'https://arxiv.org/abs/2304.13705', 'https://tonyzhaozh.github.io/aloha/', 'ACT / ALOHA', '저비용 양팔 teleoperation과 action chunking, temporal ensembling을 결합해 적은 실제 시연으로 정밀 조작을 안정화했다.', 'VLA를 쓰기 전 비교해야 할 가장 중요한 행동 모사 기준선 중 하나다.', 'action chunking, temporal ensembling, CVAE, bimanual teleoperation', 'action chunking, temporal ensembling'],
  ['diffusion-policy', 'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion', '확산 모델로 행동 궤적을 생성하는 Diffusion Policy', '2023', 'RSS', 'https://arxiv.org/abs/2303.04137', 'https://github.com/real-stanford/diffusion_policy', 'Diffusion Policy', '조건부 denoising으로 여러 가능한 행동 궤적을 생성해 다봉 조작 분포와 고차원 제어를 안정적으로 다룬다.', '단순 회귀가 평균 행동으로 무너지는 문제와 inference latency의 trade-off를 배운다.', 'conditional diffusion, receding horizon, action sequence, multimodality', 'diffusion policy, receding horizon'],
  ['open-x-embodiment', 'Open X-Embodiment: Robotic Learning Datasets and RT-X Models', '여러 로봇 데이터를 연결한 Open X-Embodiment', '2023', 'ICRA 2024', 'https://arxiv.org/abs/2310.08864', 'https://robotics-transformer-x.github.io/', 'Open X-Embodiment', '21개 기관·22개 로봇의 527 skills를 공통 형식으로 모으고 RT-X의 cross-robot transfer를 보였다.', 'VLA에서 모델만큼 중요한 observation/action schema와 데이터 정렬 문제를 정면으로 다룬다.', 'RLDS, cross-embodiment, dataset standardization, RT-X', 'RLDS, cross-embodiment'],
  ['octo', 'Octo: An Open-Source Generalist Robot Policy', '공개 generalist robot policy Octo', '2024', 'Robotics: Science and Systems', 'https://arxiv.org/abs/2405.12213', 'https://github.com/octo-models/octo', 'Octo', 'Open X의 80만 trajectory 위에서 학습한 Transformer policy로, 새 센서와 action space에 효율적으로 적응하는 공개 기준선을 제공한다.', 'OpenVLA보다 작은 모델로 사전학습 policy 적응의 기본기를 익히기 좋다.', 'generalist policy, language conditioning, action normalization, finetuning', 'generalist policy, action space'],
  ['openvla', 'OpenVLA: An Open-Source Vision-Language-Action Model', '공개 7B Vision-Language-Action 모델 OpenVLA', '2024', 'Robotics: Science and Systems', 'https://arxiv.org/abs/2406.09246', 'https://github.com/openvla/openvla', 'OpenVLA', 'Llama 2와 DINOv2·SigLIP 시각 표현을 결합하고 97만 실제 로봇 데모로 학습한 공개 VLA로, LoRA·양자화까지 제공한다.', '실제 VLA fine-tuning을 시작할 때 가장 재현 가능한 주축이다.', 'Prismatic VLM, action discretization, LoRA, quantization', 'VLA fine-tuning, LoRA'],
  ['pi0', 'pi0: A Vision-Language-Action Flow Model for General Robot Control', 'flow matching 행동 생성의 pi0', '2024', 'arXiv preprint', 'https://arxiv.org/abs/2410.24164', 'https://www.physicalintelligence.company/blog/pi0', 'pi0', '사전학습 VLM의 의미 지식과 flow matching action expert를 결합해 양팔·모바일 조작의 연속 행동을 생성한다.', '이산 action token을 넘어서 더 빠르고 매끄러운 행동 생성을 탐색하는 흐름을 대표한다.', 'flow matching, VLM backbone, continuous action, multi-embodiment', 'flow matching, continuous action'],
  ['smolvla', 'SmolVLA: A Vision-Language-Action Model for Affordable and Efficient Robotics', '소형·공개·비동기 추론 VLA, SmolVLA', '2025', 'arXiv preprint', 'https://arxiv.org/abs/2506.01844', 'https://github.com/huggingface/lerobot', 'SmolVLA', '450M 규모와 community data, asynchronous inference로 소비자급 하드웨어에서 VLA를 학습·실행하려는 공개 연구다.', '현장 edge 장치에서 비용·지연·데이터 품질을 함께 보려는 경우 가장 실무적인 시작점이다.', '450M model, asynchronous inference, LeRobot, community data', 'asynchronous inference, LeRobot'],
  ['qwen-vla', 'Qwen-VLA: Unifying Vision-Language-Action Modeling across Tasks, Environments, and Robot Embodiments', 'DiT 행동 decoder로 통합한 Qwen-VLA', '2026', 'arXiv preprint', 'https://arxiv.org/abs/2605.30280', 'https://github.com/QwenLM/Qwen-VLA', 'Qwen-VLA', 'Qwen vision-language stack에 DiT 기반 연속 action decoder를 더하고 조작·egocentric·시뮬레이션·navigation 데이터를 함께 학습한다.', '서로 다른 task와 로봇을 하나의 행동 foundation model로 합치려는 최신 공개 방향이다.', 'DiT action decoder, heterogeneous data, trajectory generation, unified embodiment', 'DiT, unified action'],
  ['mobile-aloha', 'Mobile ALOHA: Learning Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation', '이동 양팔 조작 데이터 수집의 Mobile ALOHA', '2024', 'arXiv preprint', 'https://arxiv.org/abs/2401.02117', 'https://mobile-aloha.github.io/', 'Mobile ALOHA', 'ALOHA에 이동 베이스와 whole-body teleoperation을 더해, 테이블 밖의 긴 조작 과제를 비교적 저비용으로 수집·학습한다.', '카메라·짐벌·이동체가 있는 실제 시스템으로 확장할 때 데이터 수집 설계를 배울 수 있다.', 'mobile manipulation, whole-body teleoperation, co-training, bimanual control', 'whole-body teleoperation, mobile manipulation'],
  ['rdt-1b', 'RDT-1B: a Diffusion Foundation Model for Bimanual Manipulation', '양팔 조작용 diffusion foundation model RDT-1B', '2024', 'arXiv preprint', 'https://arxiv.org/abs/2410.07864', 'https://github.com/thu-ml/RoboticsDiffusionTransformer', 'RDT-1B', '1.2B 규모 diffusion Transformer와 물리 의미를 유지한 unified action space로 다중 로봇 양팔 조작을 사전학습한다.', 'embodiment마다 다른 action 정의를 물리적으로 정렬하는 설계가 핵심이다.', 'diffusion transformer, unified action space, bimanual manipulation, pretraining', 'unified action space, diffusion transformer'],
  ['openvla-oft', 'Fine-Tuning Vision-Language-Action Models: Optimizing Speed and Success', '속도와 성공률을 함께 다듬는 OpenVLA-OFT', '2025', 'arXiv preprint', 'https://arxiv.org/abs/2502.19645', 'https://github.com/moojink/openvla-oft', 'OpenVLA-OFT', 'parallel decoding, action chunking, 연속 action, L1 objective를 결합해 OpenVLA 적응의 처리량과 성공률을 개선하는 recipe를 분석한다.', 'VLA를 현장 control loop에 넣을 때 fine-tuning 설계가 어떤 영향을 주는지 가장 직접적으로 보여 준다.', 'parallel decoding, continuous actions, action chunking, OFT', 'parallel decoding, action chunking'],
  ['spatialvlm', 'SpatialVLM: Endowing Vision-Language Models with Spatial Reasoning Capabilities', '공간 관계를 배우는 SpatialVLM', '2024', 'arXiv preprint', 'https://arxiv.org/abs/2401.12168', 'https://spatial-vlm.github.io/', 'SpatialVLM', '검출·깊이·분할을 결합해 2D 영상에서 공간 supervision을 만들고 VLM의 정량·정성 공간 추론을 강화한다.', 'VLA가 “왼쪽·앞·가까운” 같은 표현을 실제 위치와 행동으로 바꾸는 데 필요한 보완이다.', 'spatial supervision, metric depth, open-vocabulary detection, VLM', 'spatial reasoning, metric depth'],
  ['voxposer', 'VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models', '3D affordance와 motion planning을 분리한 VoxPoser', '2023', 'CoRL', 'https://arxiv.org/abs/2307.05973', 'https://voxposer.github.io/', 'VoxPoser', 'VLM이 언어 지시를 3D value map과 constraint로 바꾸고, 기존 motion planner가 실제 궤적을 실행하는 모듈형 접근이다.', '기존 PTZ/로봇 controller를 유지하며 언어 모델을 안전하게 상위 계층에 넣는 설계와 닮아 있다.', '3D value map, affordance, constraint, motion planning', 'value map, affordance'],
  ['langgap', 'LangGap: Diagnosing and Closing the Language Gap in Vision-Language-Action Models', 'VLA의 언어 이해 빈틈을 드러내는 LangGap', '2026', 'arXiv preprint', 'https://arxiv.org/abs/2603.00592', '찾지 못함', 'LangGap', '같은 tabletop 배치에서 언어 의미만 바꾸는 benchmark로, 높은 task success가 실제 지시 이해를 보장하지 않음을 진단한다.', 'VLA 평가에서 language perturbation과 counterfactual test가 왜 필요한지 보여 주는 최신 경고다.', 'language perturbation, semantic diversity, benchmark, diagnostic', 'semantic perturbation, language gap'],
  ['safe-learning-robotics', 'Safe Learning in Robotics: From Learning-Based Control to Safe Reinforcement Learning', '로봇 학습의 안전을 체계화한 survey', '2021', 'Annual Review of Control, Robotics, and Autonomous Systems', 'https://arxiv.org/abs/2108.06266', 'https://safe-robot-learning.github.io/', 'Safe Learning in Robotics', '학습 기반 제어와 safe RL을 안전 제약, 불확실성, 검증, runtime assurance의 관점에서 정리한다.', 'VLA의 성능과 별개로 실제 장비에 필요한 safe set, fallback, human override를 설계하는 필수 배경이다.', 'safe RL, constraints, uncertainty, runtime assurance', 'runtime assurance, safe set'],
  ['gato', 'A Generalist Agent', '여러 modality를 하나의 sequence로 다룬 Gato', '2022', 'Transactions on Machine Learning Research', 'https://arxiv.org/abs/2205.06175', 'https://www.deepmind.com/publications/a-generalist-agent', 'Gato', '텍스트·이미지·조이스틱·관절 토크를 모두 token으로 표현해 단일 모델이 서로 다른 task와 embodiment를 처리하는 초기 generalist agent다.', '행동 token화의 가능성과, 단순 통합만으로는 정밀 제어가 충분하지 않은 이유를 함께 보게 한다.', 'generalist agent, multi-modal tokens, multi-task, embodiment', 'generalist agent, modality token'],
  ['gemini-robotics', 'Gemini Robotics: Bringing AI into the Physical World', 'Gemini 기반 VLA와 embodied reasoning의 분업', '2025', 'Google DeepMind technical report', 'https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/', '찾지 못함', 'Gemini Robotics', 'Gemini 2.0에 physical action 출력을 더한 VLA와, 공간 추론·계획을 맡는 ER 모델을 분리해 generality·interactivity·dexterity를 겨냥한다.', '대규모 VLA가 저수준 행동만이 아니라 상위 embodied reasoning과 결합되는 산업계 방향을 보여 준다.', 'Gemini 2.0, VLA, embodied reasoning, multi-embodiment', 'embodied reasoning, VLA'],
  ['gemini-robotics-on-device', 'Gemini Robotics On-Device brings AI to local robotic devices', '로봇 장치 안에서 동작하는 Gemini Robotics', '2025', 'Google DeepMind technical report', 'https://deepmind.google/blog/gemini-robotics-on-device-brings-ai-to-local-robotic-devices/', '찾지 못함', 'Gemini Robotics On-Device', '일반화·정교 조작·빠른 적응을 유지하면서도 robot-local 실행을 목표로 한 Gemini Robotics의 on-device 변형이다.', 'VLA를 서버가 아닌 edge 장치에 배치할 때 latency, privacy, fallback을 어떻게 평가할지 생각하게 한다.', 'on-device VLA, local inference, dexterity, adaptation', 'on-device inference, latency'],
  ['gemini-robotics-1-5', 'Gemini Robotics 1.5 brings AI agents into the physical world', '생각하며 행동하는 Gemini Robotics 1.5', '2025', 'Google DeepMind technical report', 'https://deepmind.google/blog/gemini-robotics-15-brings-ai-agents-into-the-physical-world/', '찾지 못함', 'Gemini Robotics 1.5', '고수준 embodied reasoning과 행동 VLA가 긴 과제를 더 작은 실행 구간으로 나누고, 로봇 형상 사이에서 skill을 전이하는 흐름을 제시한다.', '긴 현장 과제에서 계획·실행·성공 판정을 분리해야 하는 이유를 이해하게 한다.', 'thinking while acting, agentic robotics, cross-embodiment, long horizon', 'long-horizon, embodied reasoning']
];

function esc(value) {
  return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
}

function tagList(p) {
  return [p[7], 'VLA roadmap', p[10].split(', ')[0], 'robot learning', 'Korean study guide'];
}

function noteHtml(p, index) {
  const [slug, title, ko, year, venue, url, code, label, summary, relevance, methods, termSource] = p;
  const [termA, termB = '일반화와 closed-loop 평가'] = termSource.split(/,\s*/, 2);
  const tags = tagList(p);
  const reading = `../translations/${date}-${slug}-ko.html`;
  const codeLink = code === '찾지 못함' ? '찾지 못함' : `<a href="${esc(code)}" target="_blank" rel="noreferrer">공식 프로젝트·코드</a>`;
  return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(ko)} | VLA 연구 노트</title><link rel="stylesheet" href="../assets/style.css"></head>
<body><main class="page">
  <a class="back-link" href="../vla-study-roadmap.html">← VLA 로드맵으로 돌아가기</a>
  <section class="hero"><p class="eyebrow">VLA Reading Note ${String(index + 1).padStart(2, '0')}</p><h1>${esc(ko)}</h1><p class="lede">${esc(summary)} ${esc(relevance)}</p>
    <div class="translation-link-box"><strong>한국어 읽기본</strong><p>원문 전문을 복제하지 않고, 초록과 절별 핵심을 한국어로 재구성한 학습 페이지입니다.</p><div class="quick-links"><a href="${reading}">한국어 읽기본 열기</a><a href="${esc(url)}" target="_blank" rel="noreferrer">원문 열기</a></div></div>
    <div class="meta-grid"><div class="meta"><strong>날짜</strong>${date}</div><div class="meta"><strong>연도 / venue</strong>${esc(year)} / ${esc(venue)}</div><div class="meta"><strong>난이도 / 실무성</strong>4 / 5, 4 / 5</div><div class="meta"><strong>라이선스</strong>전문 번역 허용 여부를 개별 확인하지 않아 전문 번역은 보류</div><div class="meta"><strong>코드</strong>${codeLink}</div><div class="meta"><strong>데이터셋</strong>원문·공식 프로젝트 참조</div><div class="meta"><strong>핵심 키워드</strong>${esc(methods)}</div><div class="meta"><strong>원문</strong><a href="${esc(url)}" target="_blank" rel="noreferrer">공식 원문</a></div></div>
    <div class="tag-list">${tags.map((tag) => `<span class="tag">${esc(tag)}</span>`).join('')}</div></section>
  <section id="summary"><h2>요약</h2><div class="summary-box">${esc(summary)}</div><div class="cards"><div class="card"><span class="mini-label">한 줄 판단</span>VLA의 ${esc(label)} 관점을 이해하고, 실제 시스템의 입력·행동 계약으로 연결하기 좋은 기준 자료다.</div><div class="card"><span class="mini-label">왜 중요하나</span>${esc(relevance)}</div><div class="card"><span class="mini-label">현장 연결점</span>영상 인식 결과를 바로 제어로 보내지 말고, 관측·지시·행동·안전 검증을 분리해 기록한다.</div></div></section>
  <section id="why"><h2>왜 이 자료인가</h2><div class="grid-2"><div class="practice-box"><h3>학습 위치</h3><p>VLA 로드맵 ${index + 1}번 자료다. 앞선 시각·언어 표현과 뒤의 실제 행동 정책 사이를 연결해 읽는다.</p></div><div class="warning-box"><h3>주의할 점</h3><p>논문의 벤치마크 성공률은 특정 robot, camera, action range, control rate에서 얻은 값이다. 조류·PTZ·드론 환경으로 직접 전이한 수치가 아니다.</p></div></div><div class="cards"><div class="card"><h3>코드 확인</h3><p>${code === '찾지 못함' ? '공식 공개 코드를 이 노트에서 확인하지 못했다. 원문·공식 발표 자료의 사용 조건을 먼저 확인한다.' : '공식 프로젝트 또는 코드 링크를 기록했다. 실행 전 모델·데이터의 각 라이선스를 별도로 확인한다.'}</p></div><div class="card"><h3>번역 범위</h3><p>전문 번역 라이선스를 개별적으로 확인하기 전까지는 원문 전문을 저장하지 않는다. 별도 읽기본은 학습용 재구성이다.</p></div><div class="card"><h3>실무성 평가</h3><p>모델 자체보다 timestamp, 좌표계, 행동 단위, fallback controller, 운영자 승인 경로를 함께 설계할 때 가치가 커진다.</p></div></div></section>
  <section id="core-idea"><h2>핵심 아이디어</h2><div class="grid-2"><div class="card"><h3>방법의 중심</h3><p>${esc(methods)}을(를) 결합해, 관측과 목표로부터 다음 행동 또는 행동 구간을 예측한다. 핵심은 모든 모듈을 거대한 모델 하나로 합치는 데 있지 않고, 각 표현과 제어 신호의 의미를 일관되게 맞추는 데 있다.</p></div><div class="figure"><div class="flow"><div class="step">관측·상태</div><div class="arrow">→</div><div class="step">${esc(label)}</div><div class="arrow">→</div><div class="step">행동 후보</div><div class="arrow">→</div><div class="step">안전 검증·실행</div></div><div class="caption">원문 방법을 현장 적용 관점에서 단순화한 개념 흐름도다.</div></div></div></section>
  <section id="figures"><h2>그림과 표를 어떻게 읽을까</h2><table><thead><tr><th>원문에서 찾을 항목</th><th>뜻</th><th>실무 포인트</th></tr></thead><tbody><tr><td>System / Method Figure</td><td>입력 token, temporal context, action head의 연결 방식</td><td>camera timestamp·control Hz·좌표계가 그림에 생략되지 않았는지 확인</td></tr><tr><td>Generalization Table</td><td>새 물체·지시·장면·robot에서의 success 비교</td><td>offline loss 대신 closed-loop task success와 시도 횟수를 함께 기록</td></tr><tr><td>Ablation</td><td>${esc(methods)} 중 실제로 효과를 만든 요소</td><td>현장 재현에서는 해당 요소 하나씩 켜고 끄며 검증</td></tr></tbody></table></section>
  <section id="technical-details"><h2>기술 핵심</h2><div class="grid-3"><div class="card"><span class="mini-label">표현</span><div class="metric">관측 → token</div><p>영상, 언어, 로봇 상태를 같은 시간 기준으로 정렬한다. 새 시스템에서는 누락 프레임과 지연도 데이터로 기록한다.</p></div><div class="card"><span class="mini-label">행동</span><div class="metric">token / 연속값</div><p>행동이 이산 token인지 연속 pose인지, 한 step인지 action chunk인지에 따라 지연·부드러움·복구 능력이 달라진다.</p></div><div class="card"><span class="mini-label">평가</span><div class="metric">closed loop</div><p>성공률, safety stop, 평균 완료 시간, 복구 횟수, 새 지시·새 배치 일반화를 분리해 본다.</p></div></div></section>
  <section id="application"><h2>조류 충돌 방지 시스템에 어떻게 쓰나</h2><div class="cards"><div class="card"><h3>조류 추적</h3><p>VLA를 즉시 tracker로 쓰기보다, 검출·추적 결과를 바탕으로 다음 관측 목표를 제안하는 상위 policy로 먼저 시험한다.</p></div><div class="card"><h3>PTZ 카메라 추적</h3><p>pan/tilt/zoom의 최댓값, deadband, 제어 주기를 policy 밖의 안전 계층에서 제한하고 manual override를 보존한다.</p></div><div class="card"><h3>YOLO 데이터·학습</h3><p>VLA 연구의 데이터 다양성 원칙을 적용해 날씨·역광·거리·종·오검출·운영자 조작을 구조화해 수집한다.</p></div><div class="card"><h3>실시간 서버 운영</h3><p>모델 latency, RTSP 지연, 명령 왕복 시간을 따로 계측한다. 모델 추론이 빠르더라도 전체 제어 loop가 느리면 안전하지 않다.</p></div></div></section>
  <section id="experiment"><h2>바로 해볼 실험 3가지</h2><div class="grid-3"><div class="card"><h3>1. 표현 점검</h3><p>동일 영상 클립에서 텍스트 지시를 바꾸고 목표 선택이 바뀌는지 확인한다.</p><p><strong>측정:</strong> 지시 민감도, 잘못된 대상 선택률</p></div><div class="card"><h3>2. 제어 비교</h3><p>단일 step 제어와 action chunk/temporal smoothing을 같은 안전 상한 아래 비교한다.</p><p><strong>측정:</strong> 지연, overshoot, 복구 횟수</p></div><div class="card"><h3>3. 현장 일반화</h3><p>역광·안개·군집·가림 장면을 hold-out으로 두고 운영자 승인 결과와 비교한다.</p><p><strong>측정:</strong> 성공률, false alarm, missed event</p></div></div></section>
  <section id="terms"><h2>용어 정리</h2><table><thead><tr><th>용어</th><th>뜻</th></tr></thead><tbody><tr><td>${esc(termA)}</td><td>이 자료에서 핵심적으로 쓰이는 표현·제어 또는 학습 개념이다. 원문의 정의와 구현 단위를 함께 확인한다.</td></tr><tr><td>${esc(termB)}</td><td>일반화 또는 실제 실행 품질을 판단할 때 쓰이는 핵심 용어다.</td></tr><tr><td>Closed loop</td><td>행동 뒤의 새 관측을 다시 받아 다음 행동을 수정하는 제어 방식이다.</td></tr></tbody></table></section>
  <section id="links"><h2>링크</h2><ul><li><a href="${esc(url)}" target="_blank" rel="noreferrer">원문·공식 자료</a></li>${code === '찾지 못함' ? '' : `<li><a href="${esc(code)}" target="_blank" rel="noreferrer">공식 코드 또는 프로젝트</a></li>`}<li><a href="${reading}">한국어 읽기본</a></li><li><a href="../vla-study-roadmap.html">VLA 로드맵</a></li></ul></section>
  <section id="checklist"><h2>최종 체크리스트</h2><ul class="checklist"><li>관측과 행동의 시간축·좌표계·단위를 설명할 수 있는가?</li><li>${esc(methods)}이(가) 왜 필요한지 한 문장으로 설명할 수 있는가?</li><li>원문 benchmark와 실제 시스템 환경의 차이를 적었는가?</li><li>offline 지표와 closed-loop 성공률을 구분했는가?</li><li>안전 상한·fallback·운영자 승인 경로를 설계했는가?</li></ul></section>
</main></body></html>`;
}

function readerHtml(p, index) {
  const [slug, title, ko, year, venue, url, code, label, summary, relevance, methods, termSource] = p;
  const [termA, termB = '일반화와 closed-loop 평가'] = termSource.split(/,\s*/, 2);
  const note = `../papers/${date}-${slug}.html`;
  return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(ko)} 한국어 읽기본</title><link rel="stylesheet" href="../assets/style.css"></head>
<body><main class="page"><a class="back-link" href="${note}">← 상세 노트로 돌아가기</a>
  <section class="hero"><p class="eyebrow">Korean Reading Guide · VLA ${String(index + 1).padStart(2, '0')}</p><h1>${esc(ko)}</h1><p class="lede">원문 전문을 복제하지 않고, 학습에 필요한 논지·구조·용어를 한국어로 자세히 재구성한 읽기본입니다.</p><div class="notice" id="translation-notice"><strong>저작권·번역 고지</strong><p>이 자료는 원문의 전문 번역이 아닙니다. 원문·코드·데이터의 번역·파생 저작물 허용 라이선스를 이 항목에서 명시적으로 확인하지 못했으므로, 초록의 핵심과 방법·실험의 학습 포인트만 독자적으로 재구성했습니다.</p><p>원문: <a href="${esc(url)}" target="_blank" rel="noreferrer">공식 페이지</a></p></div><div class="meta-grid" id="paper-info"><div class="meta"><strong>Original title</strong>${esc(title)}</div><div class="meta"><strong>Korean title</strong>${esc(ko)}</div><div class="meta"><strong>Year / Venue</strong>${esc(year)} / ${esc(venue)}</div><div class="meta"><strong>Original URL</strong><a href="${esc(url)}" target="_blank" rel="noreferrer">원문</a></div><div class="meta"><strong>Code</strong>${code === '찾지 못함' ? '찾지 못함' : `<a href="${esc(code)}" target="_blank" rel="noreferrer">공식 링크</a>`}</div><div class="meta"><strong>Reading scope</strong>초록 재구성 + 절별 상세 해설</div></div></section>
  <section id="abstract-ko"><h2>초록 핵심 한국어 재구성</h2><div class="translation-block"><p>${esc(summary)}</p><p>${esc(relevance)} 이 읽기본에서는 해당 주장을 실제 제어 시스템 관점에서 해석한다. 즉 모델의 출력이 행동이라면, 그 행동이 어느 좌표계에서 어떤 빈도로 실행되고 새 관측으로 어떻게 보정되는지까지 함께 읽어야 한다.</p></div></section>
  <section id="section-by-section"><h2>절별 읽기 가이드</h2><div class="cards"><div class="card"><h3>1. 문제 설정</h3><p>기존 방법이 놓치는 일반화·데이터·행동 표현·실시간성 중 무엇을 문제로 정의하는지 찾는다. 논문이 다루는 robot와 task 범위를 먼저 표시한다.</p></div><div class="card"><h3>2. 방법</h3><p>${esc(methods)}의 역할을 분리해 읽는다. 입력 표현, 시간 문맥, action decoder, 실행·안전 계층 중 어느 부분이 학습되는지 확인한다.</p></div><div class="card"><h3>3. 학습 데이터와 적응</h3><p>데모가 어떤 camera view, action range, language annotation을 갖는지, 새 환경에 갈 때 어떤 fine-tuning 또는 calibration이 필요한지 정리한다.</p></div><div class="card"><h3>4. 실험과 한계</h3><p>task success와 일반화 설정을 보되, latency·실패 복구·안전 정지·낯선 조명/배치에서의 결과가 빠져 있지 않은지 확인한다.</p></div></div></section>
  <section id="figure-table-guide"><h2>그림·표 읽기</h2><table><thead><tr><th>찾을 대상</th><th>읽는 법</th><th>질문</th></tr></thead><tbody><tr><td>구성도</td><td>관측·언어·상태가 어디에서 합쳐지고 행동이 어디에서 생성되는지 추적한다.</td><td>안전 controller는 모델 안인가, 밖인가?</td></tr><tr><td>정량 표</td><td>동일 robot/데이터/제어 주기인지 맞춘 뒤 success를 비교한다.</td><td>새 task와 새 embodiment를 구분했는가?</td></tr><tr><td>실패 사례</td><td>오인식, 지연, 가림, language ambiguity를 별도 실패 유형으로 기록한다.</td><td>내 현장 로그에 같은 유형이 있는가?</td></tr></tbody></table></section>
  <section id="important-terms"><h2>중요 용어</h2><div class="grid-3"><div class="card"><h3>${esc(termA)}</h3><p>원문에서 정의와 구현 단위를 확인한다. 용어 이름만 같아도 데이터 형식과 제어 주기는 다를 수 있다.</p></div><div class="card"><h3>${esc(termB)}</h3><p>일반화 또는 policy 출력의 품질과 연결되는 개념이다.</p></div><div class="card"><h3>Embodiment</h3><p>센서, 관절, action range, camera mounting을 포함한 로봇의 물리적 형상과 인터페이스다.</p></div></div></section>
  <section id="practical-notes"><h2>실무 읽기 노트</h2><div class="grid-3"><div class="practical"><h3>데이터</h3><p>timestamp·frame drop·operator input·환경 조건을 원시 영상과 함께 남긴다.</p></div><div class="practical"><h3>제어</h3><p>모델 출력에는 range limiter, timeout, fallback, human override를 독립적으로 둔다.</p></div><div class="practical"><h3>평가</h3><p>성공률뿐 아니라 false command, recovery, end-to-end latency를 기록한다.</p></div></div></section>
  <section id="original-links"><h2>원문 링크</h2><ul><li><a href="${esc(url)}" target="_blank" rel="noreferrer">원문·공식 자료</a></li>${code === '찾지 못함' ? '' : `<li><a href="${esc(code)}" target="_blank" rel="noreferrer">공식 코드 또는 프로젝트</a></li>`}<li><a href="${note}">상세 노트</a></li></ul></section>
  <section id="reading-checklist"><h2>읽기 체크리스트</h2><ul class="checklist"><li>문제 설정과 실제 deployment 환경을 분리해 적었는가?</li><li>입력·행동·시간축의 정의를 확인했는가?</li><li>원문 수치를 다른 로봇·카메라 환경에 그대로 일반화하지 않았는가?</li><li>라이선스가 불명확한 원문 전문을 이 페이지에 복제하지 않았는가?</li></ul></section>
</main></body></html>`;
}

function jsonRecord(p) {
  const [slug, title, , year, venue, url, code, label, summary] = p;
  return {
    date, title, year, venue, url, pdf_url: url.includes('arxiv.org/abs/') ? url.replace('/abs/', '/pdf/') : '',
    code, dataset: '원문·공식 프로젝트 참조', tags: tagList(p), category, difficulty: 4, practicality: 4,
    html: `papers/${date}-${slug}.html`, full_translation_html: '', translation_type: 'detailed_korean_reading_guide',
    translation_status: 'completed', translation_scope: '원문 전문을 복제하지 않고, 초록 핵심·절별 학습 포인트·용어·실험 관점을 한국어로 재구성한 읽기본을 제공',
    license_note: '원문 페이지는 확인했지만 이 항목에서 번역·파생 저작물을 명시적으로 허용하는 논문 라이선스를 개별 확인하지 못했습니다. 따라서 공개 저장소에는 원문 전문 한국어 번역을 넣지 않고 상세 노트와 한국어 읽기본만 제공합니다. 코드 링크는 기록했으나 코드 라이선스는 실행 전 공식 저장소에서 다시 확인해야 합니다. 독립 데이터셋 라이선스는 원문·공식 프로젝트를 참조해야 합니다.',
    one_line_summary: summary,
    translation_html: `translations/${date}-${slug}-ko.html`
  };
}

for (const [index, paper] of papers.entries()) {
  fs.writeFileSync(path.join(root, 'papers', `${date}-${paper[0]}.html`), noteHtml(paper, index));
  fs.writeFileSync(path.join(root, 'translations', `${date}-${paper[0]}-ko.html`), readerHtml(paper, index));
}

const jsonPath = path.join(root, 'papers.json');
const existing = JSON.parse(fs.readFileSync(jsonPath, 'utf8')).filter((item) => !papers.some((paper) => item.html === `papers/${date}-${paper[0]}.html`));
fs.writeFileSync(jsonPath, `${JSON.stringify(papers.map(jsonRecord).concat(existing), null, 2)}\n`);

const indexPath = path.join(root, 'index.html');
let indexHtml = fs.readFileSync(indexPath, 'utf8');
const marker = '<tbody id="paperRows">';
const rows = papers.map((p) => {
  const [slug, title, , , , , , label] = p;
  const tags = tagList(p).slice(0, 4).map((tag) => `<span class="tag">${esc(tag)}</span>`).join('');
  return `            <tr data-category="${categoryKey}"><td>${date}</td><td><span class="category-badge cat-rt">실시간 컴퓨터 비전</span></td><td>${esc(title)}</td><td><div class="tag-list">${tags}</div></td><td>4 / 5</td><td><span class="score">4 / 5</span></td><td>${esc(label)}, VLA, robot learning</td><td><a href="papers/${date}-${slug}.html">노트 열기</a></td><td><a href="translations/${date}-${slug}-ko.html">읽기본 열기</a></td><td>라이선스 불명확으로 보류</td></tr>`;
}).join('\n');
const stalePattern = new RegExp(`\\n\\s*<tr data-category="rt">(?:(?!<tr data-category=).|\\n)*?papers/${date}-(?:${papers.map((p) => p[0]).join('|')})\\.html[\\s\\S]*?</tr>`, 'g');
indexHtml = indexHtml.replace(stalePattern, '');
indexHtml = indexHtml.replace(marker, `${marker}\n${rows}`);
fs.writeFileSync(indexPath, indexHtml);

console.log(`Generated ${papers.length} detailed notes and Korean reading guides.`);
